
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deploy.yml
- frontend/deploy.yml
- backend/service.yml
- frontend/service.yml
  

images:
- name: 649795374786.dkr.ecr.us-east-1.amazonaws.com/dvn-nov-workshop/production/backend
  newName: 649795374786.dkr.ecr.us-east-1.amazonaws.com/dvn-nov-workshop/production/backend
  newTag: d06b7eef7328ea5a8f43dc5c3aaad5701ee0e22a
- name: 649795374786.dkr.ecr.us-east-1.amazonaws.com/dvn-nov-workshop/production/frontend
  newName: 649795374786.dkr.ecr.us-east-1.amazonaws.com/dvn-nov-workshop/production/frontend
  newTag: 833f241bef0f8133b940e754a61c6115bb2ddde3
